### ISSUE TITLE
 "mocha-teamcity-reporter" reporter blew up with error:

### ISSUE THREAD

**Issue by alan-agius4** [travisjeffery/mocha-teamcity-reporter#21]
20:19][Step 4/4] "mocha-teamcity-reporter" reporter blew up with error:
[08:20:19][Step 4/4] ReferenceError: window is not defined
[08:20:19][Step 4/4]   at Object.<anonymous> (D:\tc\ba1\work\39f0d6d839da2ca9\src\node_modules\mocha-teamcity-reporter\lib\teamcity.js:25:5)
[08:20:19][Step 4/4]   at Module._compile (module.js:541:32)

Version: 1.1.0

Previously. 1.0.2 works fine

**Comment by woraphol-j** [comment]
Confirmed this behavior. Getting the same error as well. Running on Node.js environment (Node 6.3.4)

**Comment by rajwilkhu** [comment]
Same issue - all our CI builds are broken :-(

[06:52:21][Step 2/2] "mocha-teamcity-reporter" reporter blew up with error:
[06:52:21][Step 2/2] ReferenceError: window is not defined
[06:52:21][Step 2/2]     at Object.<anonymous> (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\mocha-teamcity-reporter\lib\teamcity.js:25:5)
[06:52:21][Step 2/2]     at Module._compile (module.js:556:32)
[06:52:21][Step 2/2]     at Object.Module._extensions..js (module.js:565:10)
[06:52:21][Step 2/2]     at Module.load (module.js:473:32)
[06:52:21][Step 2/2]     at tryModuleLoad (module.js:432:12)
[06:52:21][Step 2/2]     at Function.Module._load (module.js:424:3)
[06:52:21][Step 2/2]     at Module.require (module.js:483:17)
[06:52:21][Step 2/2]     at require (internal/module.js:20:19)
[06:52:21][Step 2/2]     at Mocha.reporter (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\mocha\lib\mocha.js:151:21)
[06:52:21][Step 2/2]     at new Mocha (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\mocha\lib\mocha.js:88:8)
[06:52:21][Step 2/2]     at module.exports (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\gulp-mocha\index.js:12:14)
[06:52:21][Step 2/2]     at Gulp.gulp.task (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\@informa\tasks.pharma\lib\index.js:112:15)
[06:52:21][Step 2/2]     at module.exports (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\orchestrator\lib\runTask.js:34:7)
[06:52:21][Step 2/2]     at Gulp.Orchestrator._runTask (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\orchestrator\index.js:273:3)
[06:52:21][Step 2/2]     at Gulp.Orchestrator._runStep (C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\orchestrator\index.js:214:10)
[06:52:21][Step 2/2]     at C:\BuildAgent\work\45d48cc6de5b6cea\node_modules\orchestrator\index.js:279:18

**Comment by rajwilkhu** [comment]
Submitted a PR to fix this issue: https://github.com/travisjeffery/mocha-teamcity-reporter/pull/22

**Comment by ts-taiye** [comment]
Have the same error, node v4.4.0

**Comment by travisjeffery** [comment]
Just pushed v1.1.1 fixing this, thanks @rajwilkhu
